= chrony-formula

https://travis-ci.com/saltstack-formulas/chrony-formula[image:https://travis-ci.com/saltstack-formulas/chrony-formula.svg?branch=master[Travis CI Build Status]]
https://github.com/semantic-release/semantic-release[image:https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic--release-e10079.svg[Semantic Release]]

Formula to set up and configure chrony

== General notes

See the full
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html[SaltStack
Formulas installation and usage instructions].

If you are interested in writing or contributing to formulas, please pay
attention to the
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#writing-formulas[Writing
Formula Section].

If you want to use this formula, please pay attention to the `FORMULA`
file and/or `git tag`, which contains the currently released version.
This formula is versioned according to http://semver.org/[Semantic
Versioning].

See
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#versioning[Formula
Versioning Section] for more details.

== Contributing to this repo

*Commit message formatting is significant!!*

Please see
xref:main::CONTRIBUTING.adoc[How
to contribute] for more details.

== Available states

=== `chrony`

_Meta-state (This is a state that includes other states)_.

This installs the chrony package, manages the chrony configuration file
and then starts the associated chrony service.

=== `chrony.package`

This state will install the chrony package only.

=== `chrony.config`

This state will configure the chrony service and has a dependency on
`chrony.install` via include list.

=== `chrony.service`

This state will start the chrony service and has a dependency on
`chrony.config` via include list.

=== `chrony.clean`

_Meta-state (This is a state that includes other states)_.

this state will undo everything performed in the `chrony` meta-state in
reverse order, i.e. stops the service, removes the configuration file
and then uninstalls the package.

=== `chrony.service.clean`

This state will stop the chrony service and disable it at boot time.

=== `chrony.config.clean`

This state will remove the configuration of the chrony service and has a
dependency on `chrony.service.clean` via include list.

=== `chrony.package.clean`

This state will remove the chrony package and has a depency on
`chrony.config.clean` via include list.
